<?php

use App\Post;
use App\PostComment;
use Illuminate\Database\Seeder;

class PostCommentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PostComment::truncate();

        $posts = Post::all()->where('id', '<=', 15);

        foreach ($posts as $key => $post) {
            for ($i = 1; $i <= ($key + 1); $i++) {
                PostComment::create([
                    'title' => "contenido $post->title",
                    'message' => "Laravel includes a simple method of seeding your database with test data using seed classes. All seed classes are stored in the database/seeds directory. Seed classes may have any name you wish, but probably should follow some sensible convention, such as UsersTableSeeder, etc. By default, a DatabaseSeeder class is defined for you. From this class, you may use the call method to run other seed classes, allowing you to control the seeding order. Writing Seeders To generate a seeder, execute the make:seeder Artisan command. All seeders generated by the framework will be placed in the database/seeds directory:",
                    'user_id' => 3,
                    'post_id' => $post->id,
                ]);
            }
        }
    }
}
